# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products/product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16products/product.proto\x12\x08products\x1a\x1bgoogle/protobuf/empty.proto\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x11\n\tis_bought\x18\x04 \x01(\x08\"\x14\n\x12ProductListRequest\"$\n\x16ProductRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xaf\x02\n\x11ProductController\x12;\n\x04List\x12\x1c.products.ProductListRequest\x1a\x11.products.Product\"\x00\x30\x01\x12\x30\n\x06\x43reate\x12\x11.products.Product\x1a\x11.products.Product\"\x00\x12\x41\n\x08Retrieve\x12 .products.ProductRetrieveRequest\x1a\x11.products.Product\"\x00\x12\x30\n\x06Update\x12\x11.products.Product\x1a\x11.products.Product\"\x00\x12\x36\n\x07\x44\x65stroy\x12\x11.products.Product\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products.product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=65
  _PRODUCT._serialized_end=136
  _PRODUCTLISTREQUEST._serialized_start=138
  _PRODUCTLISTREQUEST._serialized_end=158
  _PRODUCTRETRIEVEREQUEST._serialized_start=160
  _PRODUCTRETRIEVEREQUEST._serialized_end=196
  _PRODUCTCONTROLLER._serialized_start=199
  _PRODUCTCONTROLLER._serialized_end=502
# @@protoc_insertion_point(module_scope)
