# Generated by Django 4.1.1 on 2022-10-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Наименование')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('is_bought', models.BooleanField(default=False, verbose_name='Куплен')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
